# Generated by Django 2.2.3 on 2020-01-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_templates',
            name='user_display_name',
            field=models.BooleanField(choices=[(True, 'USE USER FIRSTNAME LASTNAME'), (False, 'CUSTOM NAME FOR THIS TEMPLATE')], db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='alternative_phone',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='official_email',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='official_phone',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_email',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_phone',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
