# Generated by Django 2.2.4 on 2020-03-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='invoice_no',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
