# Generated by Django 3.0.4 on 2020-03-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='service_recipient_address',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
