# Generated by Django 3.0.4 on 2020-03-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200319_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='subtotal_inc_tax',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
