# Generated by Django 2.2.4 on 2020-03-08 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_invoicemodel_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_person', to='app.Contacts'),
        ),
    ]
