# Generated by Django 2.2.3 on 2020-01-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200128_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
    ]
