# Generated by Django 2.2.3 on 2020-02-20 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200221_0342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_addresses',
            old_name='contact_name',
            new_name='contact_person',
        ),
    ]
