# Generated by Django 2.2.4 on 2020-03-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200322_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address_details',
            name='is_billing_address_diff',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False),
        ),
    ]
