# Generated by Django 2.2.3 on 2019-11-07 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contacts_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='contact_email',
        ),
        migrations.AddField(
            model_name='contacts',
            name='created_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='is_customer',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='contacts',
            name='is_vendor',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='contacts',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='updated_on',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='Contacts_Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('is_official', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], db_index=True, default=True)),
                ('is_primary', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], db_index=True, default=True)),
                ('pan', models.CharField(db_index=True, max_length=10)),
                ('gstin', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('tds', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=20, null=True)),
                ('invoice_terms', models.IntegerField(blank=True, choices=[(1, 'On Due Date'), (2, '10 Days'), (3, '20 Days'), (4, '30 Days'), (5, '60 Days'), (6, '90 Days')], db_index=True, null=True)),
                ('bills_terms', models.IntegerField(blank=True, choices=[(1, 'On Due Date'), (2, '10 Days'), (3, '20 Days'), (4, '30 Days'), (5, '60 Days'), (6, '90 Days')], db_index=True, null=True)),
                ('created_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_on', models.DateTimeField(db_index=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Contacts')),
            ],
            options={
                'verbose_name_plural': 'contacts_email_tbl',
            },
        ),
        migrations.CreateModel(
            name='Contact_Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(db_index=True, max_length=250)),
                ('is_billing_address', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], db_index=True, default=False)),
                ('is_shipping_address', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], db_index=True, default=False)),
                ('same_billing_shipping_address', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], db_index=True, default=False)),
                ('created_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_on', models.DateTimeField(db_index=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Contacts')),
            ],
            options={
                'verbose_name_plural': 'contacts_address_details_tbl',
            },
        ),
        migrations.CreateModel(
            name='Contact_Account_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.BigIntegerField(db_index=True, null=True)),
                ('account_holder_name', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('ifsc_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('bank_branch_name', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('created_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_on', models.DateTimeField(db_index=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Contacts')),
            ],
            options={
                'verbose_name_plural': 'contacts_account_details_tbl',
            },
        ),
    ]
