# Generated by Django 2.2.4 on 2020-03-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_invoicemodel_sales_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='invoice_type',
            field=models.BooleanField(blank=True, choices=[(False, 'One Time'), (True, 'Recurring')], db_index=True, default=False, null=True),
        ),
    ]
