# Generated by Django 2.2.3 on 2020-01-29 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200129_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tax_details',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Contacts'),
        ),
        migrations.AddField(
            model_name='user_tax_details',
            name='is_user',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user_tax_details',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
