# Generated by Django 3.0.4 on 2020-03-21 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_invoicemodel_subtotal_inc_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Email_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_user', models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False)),
                ('email', models.EmailField(db_index=True, max_length=254, null=True)),
                ('is_official', models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=True)),
                ('is_personal', models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=True)),
                ('created_on', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('updated_on', models.DateTimeField(db_index=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Contacts')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user_email_tbl',
            },
        ),
        migrations.RemoveField(
            model_name='contact_addresses',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contacts_email',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_vendor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='official_email',
        ),
        migrations.AddField(
            model_name='profile',
            name='customer_type',
            field=models.IntegerField(blank=True, choices=[(1, 'CUSTOMER'), (2, 'VENDOR'), (3, 'EMPLOYEE'), (4, 'OTHERS')], db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='user_account_details',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Contacts'),
        ),
        migrations.AddField(
            model_name='user_account_details',
            name='is_user',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='user_address_details',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Contacts'),
        ),
        migrations.AddField(
            model_name='user_address_details',
            name='is_user',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salutation',
            field=models.IntegerField(blank=True, choices=[(0, 'Mr.'), (1, 'Mrs.'), (2, 'Miss'), (3, 'Dr.'), (4, 'Ms.'), (5, 'Prof.'), (6, 'Rev.'), (7, 'Lady'), (8, 'Sir'), (9, 'Capt.'), (10, 'Major'), (11, 'Lt.-Col.'), (12, 'Col.'), (13, 'Lady'), (14, 'Lt.-Cmdr.'), (15, 'The Hon.'), (16, 'Cmdr.'), (17, 'Flt. Lt.'), (18, 'Brgdr.'), (19, 'Judge'), (20, 'Lord'), (21, 'The Hon. Mrs'), (22, 'Wng. Cmdr.'), (23, 'Group Capt.'), (24, 'Rt. Hon. Lord'), (25, 'Revd. Father'), (26, 'Revd Canon'), (27, 'Maj.-Gen.'), (28, 'Air Cdre.'), (29, 'Viscount'), (30, 'Dame'), (31, 'Rear Admrl.')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='user_account_details',
            name='created_on',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_account_details',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_address_details',
            name='created_on',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_address_details',
            name='is_billing_address',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user_address_details',
            name='is_shipping_address',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='user_address_details',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_tax_details',
            name='as_of',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.DeleteModel(
            name='Contact_Account_Details',
        ),
        migrations.DeleteModel(
            name='Contact_Addresses',
        ),
        migrations.DeleteModel(
            name='Contacts_Email',
        ),
    ]
