# Generated by Django 2.2.3 on 2020-01-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_invoice_templates_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='provider_billing_address',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='provider_shipping_address',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='recipient_billing_address',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='recipient_shipping_address',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
