# Generated by Django 2.2.4 on 2019-11-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191107_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts_email',
            name='bills_terms',
        ),
        migrations.RemoveField(
            model_name='contacts_email',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='contacts_email',
            name='invoice_terms',
        ),
        migrations.RemoveField(
            model_name='contacts_email',
            name='pan',
        ),
        migrations.RemoveField(
            model_name='contacts_email',
            name='tds',
        ),
        migrations.AddField(
            model_name='contacts',
            name='bills_terms',
            field=models.IntegerField(blank=True, choices=[(1, 'On Due Date'), (2, '10 Days'), (3, '20 Days'), (4, '30 Days'), (5, '60 Days'), (6, '90 Days')], db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='gstin',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='invoice_terms',
            field=models.IntegerField(blank=True, choices=[(1, 'On Due Date'), (2, '10 Days'), (3, '20 Days'), (4, '30 Days'), (5, '60 Days'), (6, '90 Days')], db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='pan',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='tds',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
