# Generated by Django 2.2.3 on 2020-01-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200128_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts_email',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
    ]
