# Generated by Django 2.2.3 on 2020-01-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200129_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='bills_terms',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='invoice_terms',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='is_vendor',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='preferred_delivery',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='preferred_payment_method',
        ),
        migrations.AddField(
            model_name='contacts',
            name='customer_type',
            field=models.IntegerField(blank=True, choices=[(1, 'CUSTOMER'), (2, 'VENDOR'), (3, 'EMPLOYEE'), (4, 'OTHERS')], db_index=True, default=1, null=True),
        ),
    ]
