# Generated by Django 3.0.4 on 2020-03-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200321_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address_details',
            name='contact_person',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
