# Generated by Django 2.2.4 on 2020-03-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_invoicemodel_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
