# Generated by Django 2.2.3 on 2020-02-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200221_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_addresses',
            name='is_billing_address',
            field=models.BooleanField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='contact_addresses',
            name='is_shipping_address',
            field=models.BooleanField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False, null=True),
        ),
    ]
