# Generated by Django 2.2.4 on 2020-03-27 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200327_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_name', models.CharField(max_length=250)),
                ('bundle_selling_price', models.FloatField(db_index=True, default=0, null=True)),
                ('bundle_cost_price', models.FloatField(db_index=True, default=0, null=True)),
                ('bundle_marked_price', models.FloatField(db_index=True, default=0, null=True)),
                ('bundle_discount', models.FloatField(db_index=True, default=0, null=True)),
                ('bundle_gst', models.FloatField(db_index=True, default=0, null=True)),
                ('bundle_qty', models.IntegerField(db_index=True, default=0, null=True)),
                ('bundle_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BundleProductsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BundleModel')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ProductsModel')),
            ],
        ),
    ]
