# Generated by Django 2.2.3 on 2020-01-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200128_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contacts_email',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, null=True),
        ),
    ]
