# Generated by Django 2.2.3 on 2019-11-08 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191107_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts_email',
            old_name='is_primary',
            new_name='is_personal',
        ),
    ]
