# Generated by Django 2.2.3 on 2020-02-21 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200221_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_addresses',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Contacts'),
        ),
    ]
