# Generated by Django 2.2.4 on 2020-03-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_invoicemodel_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='terms_invoice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
