# Generated by Django 2.2.4 on 2020-03-08 03:08

import app.models.contacts_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200308_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to=app.models.contacts_model.attachments_rename),
        ),
    ]
