# Generated by Django 2.2.4 on 2020-03-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bundlemodel_bundleproductsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account_details',
            name='account_number',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
