# Generated by Django 2.2.3 on 2020-01-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200123_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='shipping',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
