# Generated by Django 2.2.3 on 2020-02-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200129_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectpartial',
            name='collection_status',
            field=models.IntegerField(choices=[(1, 'Collection Expected'), (2, 'Collected')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='salutation',
            field=models.IntegerField(choices=[(0, 'Mr.'), (1, 'Mrs.'), (2, 'Miss'), (3, 'Dr.'), (4, 'Ms.'), (5, 'Prof.'), (6, 'Rev.'), (7, 'Lady'), (8, 'Sir'), (9, 'Capt.'), (10, 'Major'), (11, 'Lt.-Col.'), (12, 'Col.'), (13, 'Lady'), (14, 'Lt.-Cmdr.'), (15, 'The Hon.'), (16, 'Cmdr.'), (17, 'Flt. Lt.'), (18, 'Brgdr.'), (19, 'Judge'), (20, 'Lord'), (21, 'The Hon. Mrs'), (22, 'Wng. Cmdr.'), (23, 'Group Capt.'), (24, 'Rt. Hon. Lord'), (25, 'Revd. Father'), (26, 'Revd Canon'), (27, 'Maj.-Gen.'), (28, 'Air Cdre.'), (29, 'Viscount'), (30, 'Dame'), (31, 'Rear Admrl.')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salutation',
            field=models.IntegerField(choices=[(0, 'Mr.'), (1, 'Mrs.'), (2, 'Miss'), (3, 'Dr.'), (4, 'Ms.'), (5, 'Prof.'), (6, 'Rev.'), (7, 'Lady'), (8, 'Sir'), (9, 'Capt.'), (10, 'Major'), (11, 'Lt.-Col.'), (12, 'Col.'), (13, 'Lady'), (14, 'Lt.-Cmdr.'), (15, 'The Hon.'), (16, 'Cmdr.'), (17, 'Flt. Lt.'), (18, 'Brgdr.'), (19, 'Judge'), (20, 'Lord'), (21, 'The Hon. Mrs'), (22, 'Wng. Cmdr.'), (23, 'Group Capt.'), (24, 'Rt. Hon. Lord'), (25, 'Revd. Father'), (26, 'Revd Canon'), (27, 'Maj.-Gen.'), (28, 'Air Cdre.'), (29, 'Viscount'), (30, 'Dame'), (31, 'Rear Admrl.')], db_index=True, default=0),
        ),
    ]
