# Generated by Django 2.2.4 on 2020-03-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200327_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlemodel',
            name='bundle_sku',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bundlemodel',
            name='bundle_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
