# Generated by Django 2.2.3 on 2020-03-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_invoicemodel_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='adjustment',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='frequency',
            field=models.IntegerField(blank=True, choices=[(0, 'WEEKLY'), (1, 'MONTHLY'), (2, 'QUARTERLY'), (2, 'YEARLY')], null=True),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='subtotal',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='total',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
