# Generated by Django 2.2.3 on 2020-01-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_invoice_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='provider_shipping_address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='recipient_billing_address',
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
