# Generated by Django 2.2.3 on 2020-01-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200123_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='provider_billing_address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='recipient_shipping_address',
        ),
    ]
