# Generated by Django 2.2.4 on 2020-02-07 04:09

import app.models.contacts_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_productsmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='attachements',
            field=models.FileField(blank=True, db_index=True, null=True, upload_to=app.models.contacts_model.attachments_rename),
        ),
    ]
