# Generated by Django 2.2.3 on 2020-01-23 13:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_auto_20200123_1807'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoice',
            new_name='InvoiceModel',
        ),
    ]
