# Generated by Django 2.2.4 on 2020-03-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200328_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_address_details',
            name='is_billing_address_diff',
        ),
    ]
