# Generated by Django 2.2.3 on 2019-11-13 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_contacts_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_state_code', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('recipient_state_code', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('provider_gstin', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('recipient_gstin', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('provider_pan', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('sac_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('service_description', models.TextField(blank=True, null=True)),
                ('total_amount', models.FloatField(db_index=True, default=0)),
                ('cgst', models.FloatField(db_index=True, default=0)),
                ('igst', models.FloatField(db_index=True, default=0)),
                ('sgst', models.FloatField(db_index=True, default=0)),
                ('total_gst', models.FloatField(db_index=True, default=0)),
                ('total_amount_after_tax', models.FloatField(db_index=True, default=0)),
                ('service_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Contacts')),
            ],
            options={
                'verbose_name_plural': 'invoice_tbl',
            },
        ),
    ]
