# Generated by Django 2.2.3 on 2020-02-10 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_productcategory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmodel',
            name='product_category',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
