# Generated by Django 2.2.3 on 2019-11-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
