# Generated by Django 2.2.4 on 2020-02-14 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_auto_20200211_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='is_purchase',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='is_sales',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='unit',
            field=models.IntegerField(choices=[(0, 'Kilogram'), (1, 'grams'), (2, 'ounce'), (3, 'pound'), (4, 'tons'), (5, 'metric tons'), (6, 'carat'), (7, 'furlong'), (8, 'Inches'), (9, 'foot'), (10, 'yard'), (11, 'mile'), (12, 'Meter'), (13, 'Millimetres '), (14, 'square feet'), (15, 'square metre'), (16, 'centimetre'), (17, 'Bucket'), (18, 'Bag'), (19, 'Bowl'), (20, 'Box'), (21, 'Card'), (22, 'Case'), (23, 'Carton'), (24, 'Dozen'), (25, 'Each'), (26, 'Gallon'), (27, 'Gross'), (28, 'Kit'), (29, 'Set'), (30, 'Sheet'), (31, 'Tube'), (32, 'Pack'), (31, 'teaspoon'), (33, 'tablespoon'), (34, 'cup'), (35, 'pint'), (36, 'quart'), (37, 'milliliter'), (38, 'liter')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounts_name', models.CharField(db_index=True, max_length=250)),
                ('is_active', models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
