# Generated by Django 2.2.3 on 2020-01-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200125_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='preferred_currency',
            field=models.IntegerField(choices=[(0, 'ANY'), (1, 'RUPEES'), (2, 'USD'), (3, 'EURO'), (4, 'Pound')], db_index=True, default=1),
        ),
    ]
