# Generated by Django 2.2.3 on 2020-01-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200125_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='preferred_delivery',
            field=models.IntegerField(choices=[(0, 'Any'), (1, 'Print later'), (2, 'Send Later')], db_index=True, default=0),
        ),
    ]
