# Generated by Django 2.2.3 on 2019-12-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20191116_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_addresses',
            name='city',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='contact_addresses',
            name='flat_no',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='contact_addresses',
            name='pincode',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='contact_addresses',
            name='state',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='contact_addresses',
            name='street',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
