# Generated by Django 2.2.4 on 2020-02-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_productaccounts_is_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='manufactured_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
