# Generated by Django 2.2.4 on 2020-02-15 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_auto_20200215_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(db_index=True, max_length=250)),
                ('in_date', models.DateField(blank=True, db_index=True, null=True)),
                ('stock_cleared', models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'stock_tbl',
            },
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StockModel'),
        ),
    ]
