# Generated by Django 2.2.3 on 2019-12-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20191219_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='app_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
