# Generated by Django 2.2.4 on 2020-02-15 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200215_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(db_index=True, default=0)),
                ('unit', models.IntegerField(blank=True, choices=[(0, 'Kilogram'), (1, 'grams'), (2, 'ounce'), (3, 'pound'), (4, 'tons'), (5, 'metric tons'), (6, 'carat'), (7, 'furlong'), (8, 'Inches'), (9, 'foot'), (10, 'yard'), (11, 'mile'), (12, 'Meter'), (13, 'Millimetres '), (14, 'square feet'), (15, 'square metre'), (16, 'centimetre'), (17, 'Bucket'), (18, 'Bag'), (19, 'Bowl'), (20, 'Box'), (21, 'Card'), (22, 'Case'), (23, 'Carton'), (24, 'Dozen'), (25, 'Each'), (26, 'Gallon'), (27, 'Gross'), (28, 'Kit'), (29, 'Set'), (30, 'Sheet'), (31, 'Tube'), (32, 'Pack'), (31, 'teaspoon'), (33, 'tablespoon'), (34, 'cup'), (35, 'pint'), (36, 'quart'), (37, 'milliliter'), (38, 'liter')], db_index=True, null=True)),
                ('threshold', models.IntegerField(db_index=True, default=0)),
                ('stop_at_min_hold', models.IntegerField(db_index=True, default=0)),
                ('notify_on_threshold', models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=True)),
                ('notify_on_min_hold', models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=True)),
                ('min_hold_date', models.DateField(blank=True, db_index=True, null=True)),
                ('threshold_date', models.DateField(blank=True, db_index=True, null=True)),
                ('min_hold_notify_trigger', models.IntegerField(blank=True, choices=[(0, '5 DAYS AGO'), (1, '1 WEEK AGO'), (2, '10 DAYS AGO'), (3, '2 WEEKS AGO'), (4, '1 MONTH AGO'), (5, '45 DAYS AGO'), (6, '2 MONTHS AGO'), (7, '3 MONTHS AGO'), (8, '6 MONTHS AGO'), (9, '1 YEAR AGO')], db_index=True, null=True)),
                ('threshold_notify_trigger', models.IntegerField(blank=True, choices=[(0, '5 DAYS AGO'), (1, '1 WEEK AGO'), (2, '10 DAYS AGO'), (3, '2 WEEKS AGO'), (4, '1 MONTH AGO'), (5, '45 DAYS AGO'), (6, '2 MONTHS AGO'), (7, '3 MONTHS AGO'), (8, '6 MONTHS AGO'), (9, '1 YEAR AGO')], db_index=True, null=True)),
                ('cleared_on', models.DateField(blank=True, db_index=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProductsModel')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StockModel')),
            ],
        ),
        migrations.CreateModel(
            name='StockNotificationRemiander',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_threshold', models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('stock_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StockProduct')),
            ],
        ),
    ]
