# Generated by Django 2.2.3 on 2019-12-18 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20191219_0139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_address_details',
            options={'verbose_name_plural': 'user_address_details_tbl'},
        ),
        migrations.RenameField(
            model_name='user_address_details',
            old_name='contact',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user_address_details',
            name='contact_name',
        ),
    ]
