# Generated by Django 2.2.3 on 2019-12-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20191219_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='app_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
