# Generated by Django 2.2.4 on 2020-01-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_contacts_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='provider_billing_address',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='provider_shipping_address',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='recipient_billing_address',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='recipient_shipping_address',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
