# Generated by Django 2.2.4 on 2020-01-05 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200105_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(db_index=True, max_length=250)),
                ('template_file_path', models.CharField(db_index=True, max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Invoice_Templates'),
        ),
    ]
