# Generated by Django 2.2.4 on 2020-01-05 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0022_auto_20200105_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_templates',
            name='template_file_path',
        ),
        migrations.AddField(
            model_name='invoice_templates',
            name='design_number',
            field=models.CharField(blank=True, db_index=True, default=1, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice_templates',
            name='header_bgcolor',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice_templates',
            name='header_fgcolor',
            field=models.CharField(blank=True, default='#000000', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice_templates',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='invoice_templates',
            name='other_design_colors',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice_templates',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
