# Generated by Django 2.2.3 on 2020-01-14 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20200110_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectPartial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_due_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('collected_amount', models.FloatField(blank=True, db_index=True, null=True)),
                ('payment_type', models.IntegerField(blank=True, choices=[(1, 'Cash'), (2, 'Cheque'), (3, 'Demand Draft'), (4, 'Payment Gateway')], db_index=True, null=True)),
                ('collection_status', models.IntegerField(blank=True, choices=[(1, 'Collection Expected'), (2, 'Still Collecting'), (3, 'Collected')], db_index=True, null=True)),
                ('collection_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('collect_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Collections')),
            ],
        ),
    ]
