# Generated by Django 2.2.3 on 2020-01-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_collectpartial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectpartial',
            old_name='collected_amount',
            new_name='amount',
        ),
    ]
