# Generated by Django 2.2.3 on 2020-01-17 21:35

import app.models.invoice_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_invoice_collect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectpartial',
            name='collection_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Collection Expected'), (2, 'Collected')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_templates',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=app.models.invoice_model.logo_rename),
        ),
        migrations.AlterField(
            model_name='invoice_templates',
            name='other_design_colors',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=20, null=True),
        ),
    ]
