# Generated by Django 2.2.3 on 2020-01-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20200118_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_templates',
            name='created_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='invoice_templates',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='invoice_templates',
            name='total_usage',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_templates',
            name='design_number',
            field=models.IntegerField(choices=[(1, 'GREEN TEMPLATE'), (2, 'ORANGE TEMPLATE'), (3, 'BLUE TEMPLATE'), (4, 'WHITE TEMPLATE'), (5, 'GREY TEMPLATE'), (6, 'CUSTOM TEMPLATE')], db_index=True, default=1),
        ),
    ]
